default: &default
# adapter: sqlite3 を削除
pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
timeout: 5000

development:
<<: *default
adapter: sqlite3 # 追加
database: db/development.sqlite3

production:
<<: *default
adapter: postgresql
database: db/production.pg